# Generated by Django 4.2.6 on 2023-10-31 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Equipamento')),
                ('tipo', models.CharField(choices=[('Roteador', 'Roteador'), ('ONU', 'ONU'), ('Conector', 'Conector'), ('Cabo', 'Cabo'), ('Outros', 'Outros')], default='Roteador', max_length=25)),
                ('quantidade', models.PositiveBigIntegerField(default=1)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='equipamento_imagens')),
                ('mac', models.CharField(blank=True, max_length=17, null=True, verbose_name='Mac do Equipamento')),
                ('cadastrado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por: ')),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_cadastro_por', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por: ')),
            ],
        ),
    ]
