# Generated by Django 4.2.6 on 2023-11-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoque_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='tipo',
            field=models.CharField(choices=[('Roteador', 'Roteador'), ('ONU', 'ONU'), ('Conector', 'Conector'), ('Cabo', 'Cabos'), ('Outros', 'Outros')], default='Roteador', max_length=25),
        ),
    ]
