# Generated by Django 4.2.6 on 2023-10-31 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0002_alter_funcionario_options_alter_funcionario_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionario.funcionario', verbose_name='Funcionário')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=255)),
                ('equipamento_id', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('Imagem', models.CharField(max_length=2000)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisicao.requisicao')),
            ],
            options={
                'verbose_name': 'Item da Requisição',
                'verbose_name_plural': 'Itens da Requisição',
            },
        ),
    ]
