# Generated by Django 4.2.6 on 2023-10-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicao',
            options={'verbose_name': 'Requisição', 'verbose_name_plural': 'Requisições'},
        ),
    ]
