# Generated by Django 4.2.6 on 2023-11-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_estoque_tipo'),
        ('requisicao', '0003_requisicao_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequisicao',
            name='equipamento_id',
        ),
        migrations.AlterField(
            model_name='itemrequisicao',
            name='equipamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.estoque', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='observacao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observações'),
        ),
    ]
