# Generated by Django 4.2.6 on 2023-11-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0004_remove_itemrequisicao_equipamento_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequisicao',
            name='Imagem',
        ),
    ]
