# Generated by Django 4.2.6 on 2023-11-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0002_alter_funcionario_options_alter_funcionario_cidade'),
        ('estoque', '0003_alter_estoque_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('quantidade_saida', models.PositiveIntegerField()),
                ('equipamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.estoque', verbose_name='Equipamento')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionario.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Saida estoque',
                'verbose_name_plural': 'Saida estoque',
            },
        ),
    ]
