# Generated by Django 4.2.6 on 2023-10-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(max_length=255, verbose_name='Cidade'),
        ),
    ]
